### ISSUE TITLE
add support for metrics in prometheus exporter

### ISSUE THREAD

**Issue by rghetia** [census-instrumentation/opencensus-go#1040]
Similar to work done for stackdriver export in [metrics.go](https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/master/metrics.go)

**Comment by odeke-em** [comment]
@rghetia I already did this sometime ago in https://github.com/orijtech/prometheus-go-metrics-exporter and that's what the OpenCensus Agent uses to export to Prometheus.

But really this repo shouldn't depend on Proto but also, I thought we were moving away from using these libraries and moving to the agent?

**Comment by rghetia** [comment]
@odeke-em that is great that you already have this. Where are all the exporters going to reside? At some point all exporters need to be in one place as oppose to what we have today.

**Comment by odeke-em** [comment]
Unfortunately I don't know where those exporters are going to reside. The ones I create are under my company's Github account and I write them with a license for the OpenCensus Authors so whenever ready to be moved, it'll be a simple move.

Having said that, I think this issue can be closed. We already have this in https://github.com/census-instrumentation/opencensus-service/tree/master/exporter/prometheusexporter

**Comment by rghetia** [comment]
Reopening because we need Prometheus exporter for exporting metrics directly from core-lib without an agent

**Comment by odeke-em** [comment]
The core libraries here though cannot take a dependency on Proto, because if I recall correctly grpc-go uses this code.

I think it is about time for us to extract exporter/prometheus to census-ecosystem/prometheus-go-exporter and then provide perhaps a vanity URL or at least deprecate the exporter in here for contrib.go.opencensus.io/exporter/prometheus (obviously doing a migration to census-ecosystem).

/cc @bogdandrutu @songy23
