### ISSUE TITLE
exporter/jaeger: set the Error Attribute when Status is not OK

### ISSUE THREAD

**Issue by anthonycorbacho** [census-instrumentation/opencensus-go#1041]
**Describe the bug**
When we set the Span status to be an error
```
span.SetStatus(
			ochttp.TraceStatus(404, "NOT_FOUND"),
		)
```
I am expecting to see my span attribute to be set as `error = true`.

**To Reproduce**

Given this exemple:
```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"go.opencensus.io/exporter/jaeger"

	"go.opencensus.io/plugin/ochttp"
	"go.opencensus.io/plugin/ochttp/propagation/b3"
	"go.opencensus.io/stats/view"
	"go.opencensus.io/trace"
)

func main() {
	initJaeger("helloWorld")
	mux := http.NewServeMux()
	mux.HandleFunc("/hello", func(w http.ResponseWriter, r *http.Request) {
		_, span := trace.StartSpan(r.Context(), "helloWorld")
		defer span.End()

		// force error attribute
		// span.AddAttributes(trace.BoolAttribute("error", true))

		// set the span status
		span.SetStatus(
			ochttp.TraceStatus(404, "NOT_FOUND"),
		)
		w.WriteHeader(404)
		w.Write([]byte("Boom!"))
	})

	h := &ochttp.Handler{
		Handler:          mux,
		IsPublicEndpoint: true,
		Propagation:      &b3.HTTPFormat{},
	}

	_ = view.Register(
		ochttp.ServerRequestCountView,
		ochttp.ServerRequestBytesView,
		ochttp.ServerResponseBytesView,
		ochttp.ServerLatencyView,
		ochttp.ServerRequestCountByMethod,
		ochttp.ServerResponseCountByStatusCode)

	if err := http.ListenAndServe(":8080", h); err != nil {
		log.Fatal(err)
	}
}

func initJaeger(name string) error {
	// Register the Jaeger exporter to be able to retrieve
	// the collected spans.
	exporter, err := jaeger.NewExporter(jaeger.Options{
		CollectorEndpoint: fmt.Sprintf("http://%s", "127.0.0.1:14268/api/traces"),
		AgentEndpoint:     "127.0.0.1:6831",
		Process: jaeger.Process{
			ServiceName: name,
			Tags: []jaeger.Tag{
				jaeger.StringTag("pod-id", name),
			},
		},
	})
	if err != nil {
		return err
	}

	trace.RegisterExporter(exporter)
	trace.ApplyConfig(trace.Config{DefaultSampler: trace.AlwaysSample()})
	return nil
}
```

I am expecting to see a trace error in the attribute, but instead, I have
![screen shot 2019-03-01 at 1 53 57 pm](https://user-images.githubusercontent.com/3139557/53668716-8f7a6680-3c29-11e9-9aae-78a859d63503.png)

**Expected behavior**
The expectation is to have the `Error Attribute` set.
if I manually add `span.AddAttributes(trace.BoolAttribute("error", true))` then span is marked as error
![screen shot 2019-03-01 at 1 51 40 pm](https://user-images.githubusercontent.com/3139557/53668741-a0c37300-3c29-11e9-8ed9-b36de6e8feca.png)

**Comment by odeke-em** [comment]
Thank you for filing this issue @anthonycorbacho and welcome to the OpenCensus project!

I think that the fix for this is only isolated to the Jaeger exporter. OpenCensus-Go and ochttp manually setting the "error" attribute might tainting the pool for everyone, for example what happens on a continue? The Zipkin exporter properly handles this isolated with
https://github.com/census-instrumentation/opencensus-go/blob/22a302cdd30bb5e3c0c894c70decd0b53e96eda0/exporter/zipkin/zipkin.go#L158-L168

and the Jaeger exporter can do that too. However, might you have seen the OpenCensus Agent https://opencensus.io/agent/ as well as https://opencensus.io/exporters/supported-exporters/go/ocagent/ which will require you to have Go1.11.4 and higher as well as `GO111MODULE` in your environment?

**Comment by anthonycorbacho** [comment]
Hi @odeke-em,
Thanks a lot for taking care of this issue.

**Comment by pjanotti** [comment]
Hi - I had updated opencensus-go to v0.19.1 in a private branch of opencensus-service and some tests broke because, different than v0.19.0, the jaeger exporter adds the attribute "error" as described above. I think we shouldn't do it:

1. We don't do it consistently for all exporters so switching to a different exporter may cause the attribute to disappear (confuse to the users);
2. The [semantic convention from OT for the key "error"](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table) (used by the Jaeger UI above) is that it should be decided by the application, which makes sense, e.g.: 404 from external, likely not be an error while 404 from internal system should be treated as error;

/cc @songy23 @bogdandrutu

**Comment by odeke-em** [comment]
Thanks for the feedback @pjanotti!

>1. We don't do it consistently for all exporters so switching to a different exporter may cause the attribute to disappear (confuse to the users); 

We do it for Zipkin and Stackdriver, but also it is necessary for correctness.

>2. The semantic convention from OT for the key "error" (used by the Jaeger UI above) is that it should be decided by the application, which makes sense, e.g.: 404 from external, likely not be an error while 404 from internal system should be treated as error;

I wonder then, how does the user then know what errors have occured if we don't set this attribute?

**Comment by pjanotti** [comment]
hi odeke-me, the OT recommendation is to do this at the app level and I can see it being done at some client lib thin wrapper, but, doing it, as it is right now implemented on the exporter, the user loses control of the error tag: let's say they don't want 404s to show up as errors spans in Jaeger for certain spans, what they can do? The exporter is going to be adding it anyway if they set status to some error, so there is no option for the user other than not capturing status if they want full control of the "error" tag. See https://github.com/opentracing/specification/issues/96#issuecomment-355795243 for OT recommendation. 

A different approach that gets the automaticity that you want while allowing users to control the "error" tag is to only set it if the user didn't specify the tag "error", as it is right now they may end up with two "error" tags in jaeger. By not allowing the tag to be overwritten they can control the error tag on the desired locations, that said, this becomes the inverse of OT. Since this tag is defined for systems respecting OT it seems better to follow their approach.
