### ISSUE TITLE
exporter/stats/stackdriver: handle overflow and oversized items when adding to bundler

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#202]

**Comment by odeke-em** [comment]
So firstly I don' think is an issue, because for each addition that we make, we bundler.Add only 1 item at a time so  https://github.com/google/google-api-go-client/blob/916b9a3f1bca39e28e0bfae24d74a22ab6d6c036/support/bundler/bundler.go#L138-L140 won't ever be exceeded.

However, for complete protection, I think we should set the bundler's BufferedByteLimit to 0 i.e. Limitless because:
a) We use bundler.NewBundler https://github.com/census-instrumentation/opencensus-go/blob/588fc25bed64cd0dcd0bacc79c369501c3b3d041/exporter/stats/stackdriver/stackdriver.go#L105
to https://github.com/google/google-api-go-client/blob/916b9a3f1bca39e28e0bfae24d74a22ab6d6c036/support/bundler/bundler.go#L101-L113

which applies the default of 1G for the BufferedByteLimit at https://github.com/google/google-api-go-client/blob/916b9a3f1bca39e28e0bfae24d74a22ab6d6c036/support/bundler/bundler.go#L38

If we set it to 0, then we don't have to worry about any checks, as per https://github.com/google/google-api-go-client/blob/916b9a3f1bca39e28e0bfae24d74a22ab6d6c036/support/bundler/bundler.go#L138-L140.

What do you think?

**Comment by odeke-em** [comment]
Actually my above analysis is a little wrong and only applies to `*Bundler.BundleByteLimit`, because bundler creates a weighted semaphore in
https://github.com/google/google-api-go-client/blob/916b9a3f1bca39e28e0bfae24d74a22ab6d6c036/support/bundler/bundler.go#L115-L122
of which despite trying to set 0, we have to handle and retry.

I now think that perhaps the best option here is flush the bundler on encountering any error, applying some sort of retry/backoff.

**Comment by rakyll** [comment]
We want to have the limits and allow users to tweak them depending on their requirements, that's why we cannot go for the limitless case. The [trace exporter](https://github.com/census-instrumentation/opencensus-go/blob/master/exporter/trace/stackdriver/stackdriver.go#L131) logs if there is overflow and individually upload if the item exceeds the size restrictions to be added to the bundler. I don't think there is anything else right now.

**Comment by odeke-em** [comment]
Thank you for that information @rakyll. In that case I am going to mirror what the StackDriver trace exporter does too. Perhaps at some point we should use perhaps the same code base as the code in the trace exporter seems more comprehensive but similar to the StackDriver stats exporter.

**Comment by rakyll** [comment]
@odeke-em sharing code sounds good, we can move reusables under internal somewhere.
