### ISSUE TITLE
exporter/stats/prometheus: disable Interval window

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#214]
We currently do not support windows other than the cumulative window. Return an error saying "Interval windows are not supported for now".

**Comment by odeke-em** [comment]
Thanks for raising this, I also just noticed it that we only support cumulative windows. I wonder though if we should instead return that error from `stats`
https://github.com/census-instrumentation/opencensus-go/blob/2237b123f1e72228dd0bbe11fb038462d15f6fbb/stats/view.go#L60
because `exporter/stats/prometheus` doesn't have an exposed method for directly dealing with View.Window and the `stats.Exporter`'s `Export` method doesn't return an error so it'd be ugly to panic. what do you think about this?

**Comment by rakyll** [comment]
You can check the view window at Export once you have a ViewData the way we did for the Stackdriver exporter: https://github.com/census-instrumentation/opencensus-go/blob/master/exporter/stats/stackdriver/stackdriver.go#L168.
