### ISSUE TITLE
Avoid having to deal with tag.Map for common instrumentation use cases

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#346]
tag.Map seems like unnecessary ceremony: it is never useful to carry around a tag.Map outside of a context.Context, since the tags cannot be used for anything outside of a context. 

Instead of:
```go
import "go.opencensus.io/tag"
m, _ := tag.NewMap(ctx, m, tag.Insert(key1, value1))
ctx = tag.NewContext(ctx, m)
```

```go
import "go.opencensus.io/tag"
ctx, err := tag.NewContext(ctx, tag.Insert(key1, value1))
```
We can do this by having tag.Map implement tag.Mutator, modifying tag.NewContext to take tag.Mutator... and internally call tag.NewMap. This should preserve the existing semantics while also allowing the new short-hand. Encode/Decode functions taking a context should also be created.

**Comment by rakyll** [comment]
> since the tags cannot be used for anything outside of a context

They can be kept as a state beyond the context lifetime.

We keep these types for being able to pin the tags as state because it is anti-pattern to pin the context. For example, the following cannot be implemented via the context type.

```
type RPCInfo struct {
     m *tag.Map
}
```

See:
 

> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx:

https://golang.org/pkg/context/

In Go, it is uncommon not to expose the type stored in context even though exceptions happen. For example, if state should live beyond the lifetime of an RPC/request, it makes sense not to allow user to access it without context.

We should change the signature without removing FromContext and the Map type. Because it is the primary use case. Then, we still can allow users to read the current Map from the incoming context.

```
ctx, err := tag.NewContext(ctx, tag.Insert(key1, value1))
```

**Comment by ramonza** [comment]
Sounds good. Most users will never have to deal with propagation directly so I think NewContext should cover 90% of use cases.
