### ISSUE TITLE
exporter: support SignalFX

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-go#360]
The Java implementations supports exporting to SignalFX. It might be useful for us to have an exporter for SignalFX and make this client feature rich.

**Comment by mpetazzoni** [comment]
@odeke-em, thanks for your interest! The SignalFx exporter for `opencensus-go` is next on our list of contributions to OpenCensus. Hopefully we can start working on it very soon!

**Comment by mpetazzoni** [comment]
@rakyll does `opencensus-go` not vendor dependencies?

**Comment by rakyll** [comment]
In Go, libraries vendoring dependencies is an unsupported case for now. It causes initialization of vendored packages twice and hence breaks the packages that depend on global state.

**Comment by mpetazzoni** [comment]
I know you have a lot of experience working with Go (and even _on_ Go, if I'm not mistaken?). Me on the other hand, I have very little experience with Go and dependency management in Go has always puzzled me greatly. So without getting into a flame war about dependency management in Go, what's OpenCensus' strategy against backwards incompatible changes in one of the dependencies? Since there is no (apparent?) versioning, I'm guessing it's just pulling `master` which sounds risky. How does that work?

In all honesty I strongly dislike versioning so I'm genuinely curious to learn about an alternative.

**Comment by mpetazzoni** [comment]
That is indeed the "official" SignalFx exporter for OpenCensus in Go. It was developed as a cooperation between Google and CESARBR (contracting firm), and I participated in the code reviews.

I'm not sure what the intention is wrt to including it in `opencensus-go` or moving it into the census-instrumentation GitHub organization though.

**Comment by songy23** [comment]
https://github.com/census-ecosystem/opencensus-go-exporter-signalfx
