### ISSUE TITLE
Support Zipkin/B3 propagation format

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#362]
https://github.com/openzipkin/b3-propagation

**Comment by ramonza** [comment]
After looking into this a bit, I am going to abandon my attempt for now. Zipkin expects the client and server side of the RPC to be the same Span. OpenCensus generally creates different client and server spans. This makes it awkward to map the B3 headers onto OpenCensus. For example, OpenCensus Java (which supports B3) will always produce headers that look like root spans to Zipkin because they don't have a parent Span ID: io.opencensus.implcore.trace.propagation.B3Format#extract

Seems like the right thing to do here is to properly support the Zipkin model of sharing a server and client span if this is the user intent. This needs cooperation with the Exporter. It's a lot more work and it's not clear it's useful so I'd rather implement a more compatible model like TraceContext.

**Comment by adriancole** [comment]
The impact of doing B3 and not knowing the parent ID is that the other side
won't know if the parent-id field is missing because it is a root span or
if it is missing because it wasn't propagated. In worst case, this can
screw up the trace with excess spans thinking they are root. However, if
tracers are configured uniformly to always fork a child (supportsJoin =
false or similar), then nothing will be messed up.

https://github.com/openzipkin/zipkin/pull/1745#issuecomment-331700315

The summary guidance would be that if census cannot allow read-back of the
parent-id of the current span (such that it can be written in the B3 impl),
downstream should be configured to always fork a child (supportsJoin=false).

Note that you may later get a request to keep the parent ID available for
readback. Ex in zipkin tracers we still get people who are using a logging
approach and reconstruct traces from log files. So, they need to have the
ability to read the current parent ID. Once you have any mechanism to read
the current parent ID, you can likely re-use that in the propagation impl
for B3 as well.
