### ISSUE TITLE
propagation.HTTPFormat methods should be more specific

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#447]
Eventually, we will also have an HTTPFormat interface for tag propagation. In order for a concrete type to implement both interface, I suggest trace/propagation.HTTPFormat to be modified to:

```
type HTTPFormat interface {
    SpanContextFromRequest(req *http.Request) (sc trace.SpanContext, ok bool)
    SpanContextToRequest(sc trace.SpanContext, req *http.Request)
}
```

**Comment by odeke-em** [comment]
Yeah, I agree, SpanContext as a prefix is more descriptive.

**Comment by ramonza** [comment]
This assumes that tag propagation will be provided by a separate interface. I don't necessarily think that will be the most useful way to implement it because I suspect that tag propagation and context propagation will always be intimately tied so that having two interfaces is unnecessary.

In this case, I think FromRequest and ToRequest should translate *both* SpanContext and tags. I think it comes down to the question of whether you will want to propagate tags using one convention but span context with another and I would err on the side of not supporting that. 

At least, I would recommend that we hold off on this until we have a concrete implementation of tag propagation.
