### ISSUE TITLE
No easy way to register zpages.Handler on the default mux

### ISSUE THREAD

**Issue by rakyll** [census-instrumentation/opencensus-go#477]
It is not clear how to register the zpages.Handler on the default mux.

zpages.Handler is a mux named as a handler. Users typically assume that they can register it on the default mux on a custom path such as:

```
http.Handle("/debug", zpages.Handler)
```

But /rpcz won't be accessible either at http://localhost:port/debug/rpcz or http://localhost:port/rpcz.

I think we should bring back the AddDefaultHTTPHandlers and also export the static file handler.

/cc @ramonza

**Comment by ramonza** [comment]
Won't this work?
```
http.Handle("/debug", http.StripPrefix("/debug", zpages.Handler))
```
Like: https://golang.org/pkg/net/http/#example_FileServer_stripPrefix

**Comment by rakyll** [comment]
No, it doesnt. The difference is FileServer is implementing its own routing. We can make zpages.Handler do that.

**Comment by ramonza** [comment]
I left off the trailing /, this works as expected:

    http.Handle("/debug/", http.StripPrefix("/debug", zpages.Handler))

I am reluctant to restore AddDefaultHTTPHandlers because it doesn't seem to me likely that someone would want to install these on the root path unless they are using the DefaultServeMux *only* for debug/internal pages and registering their application handlers elsewhere (is this common?)

@rakyll What about making AddDefaultHTTPHandlers install under: `/debug/census/statusz`?

**Comment by rakyll** [comment]
I think the StripPrefix usage is great, let's get rid of AddDefaultHTTPHandlers as we already do and deprecate the others. I will create a PR to add a http.StripPrefix example.

```
http.Handle("/debug/", http.StripPrefix("/debug", zpages.Handler))
```
