### ISSUE TITLE
Consider changing randomness of traceID to 96bits + 32bit timestamp

### ISSUE THREAD

**Issue by savaki** [census-instrumentation/opencensus-go#489]
This would support all the major cloud provider's trace systems while still preserving a high degree of randomness, 96 bits.  As it stands, compatibility with AWS X-Ray is awkward when using traceIDs generated by open census.

**Comment by ramonza** [comment]
This sounds like an easy win with no downside.

Context is that X-Ray TraceIDs are defined to contain a timestamp, see: https://docs.aws.amazon.com/xray/latest/api/API_PutTraceSegments.html

@bogdandrutu any objections to this?

**Comment by odeke-em** [comment]
For now, unfortunately, I believe there is a big downside and perhaps a very critical issue:
a) X-Ray TraceIDs are hyphenated `For example, 1-58406520-a006649127e371903a2de979` as per https://docs.aws.amazon.com/xray/latest/api/API_PutTraceSegments.html -- I could be wrong though
Dealing with the hyphenation and the version ID might be easy however, and we can handle that during ExportSpan for the X-ray exporter. b) is the actual issue currently

b) X-Ray TraceIDs are of the form `Version-UNIX-Epoch-12BytesOfRandomness` where UNIX-Epoch <= (1<<31)-1 and represented in 8 bytes
Our probability sampling takes the first 8 bytes of a traceID, makes a uint64, divides that by 2 and then compares that value with the `samplingProbability * (1<<63)`

https://github.com/census-instrumentation/opencensus-go/blob/01b39586f932bbb0b4e1cb6499e454c470e9138b/trace/sampling.go#L68-L75

If we have (1<<31)-1, the max epoch is 2147483647, but unless we use a probability of 1 in ~8.59BN i.e.(1/8.59e9), we'll always sample and that is very very unrealistic expectation for a sampling probability, given that even our default sampler is 1 in 10000 (1e-4) i.e.

Since

Expression|Value
---|---
max(x) = ((1<<31)-1)>>1|1073741823
frac * 1<<63 = (1/8.59e9) * (1<<63)|1073733648.0622556

The above would mean that we cannot use any probability samplers or we'd have to majorly fix our probability sampling logic.

**Comment by ramonza** [comment]
I can't find anything in opencensus-specs that defines how the TraceID should be generated or how probability sampler should work. That's good because it means we can fix this by defining it on opencensus-specs in trace/Sampling.md. We can define TraceID generation to use a timestamp compatible with X-Ray and we can also define the Probability calculation to use a hash of the TraceID (recommend we do not specify a specific algorithm).

**Comment by rakyll** [comment]
Closed via ead56c48fbe540f3601b21ff9eeea1fb60300740.

**Comment by adriancole** [comment]
We don't use probability samplers past lower 64 bits in zipkin. that is how
we avoid that issue. the other parts seem fine unless I missed a subtle
point in the description. a breaking test would be nice.
