### ISSUE TITLE
Do not use "opencensus" as the prometheus metrics prefix

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#520]
The string "opencensus" is used as the prefix / namespace for Prometheus metrics by default. This is not likely to be useful. Maybe we should provide a better default (like os.Args[0]) or just not have a default. Seems like something you would want to set differently for each view depending on what subsystem it came from (e.g. "grpc" would be a good namespace for the gRPC views).

**Comment by rakyll** [comment]
os.Args[0] might not be the ideal prefix for all cases. For example, you want to accumulate all gRPC metrics under the same metric and breakdown by os.Args[0] if needed instead of having a separate metric for each service. Maybe we shouldn't have a default namespace.

One of the other problems is that Prometheus suggests a namespace for each subclass of metrics, e.g. "grpc" and "http". OpenCensus has a global view collection and users cannot set a new exporter for different subcomponents. This resembles me the problem explained at https://github.com/census-instrumentation/opencensus-specs/issues/26.

**Comment by ramonza** [comment]
I think we should not have a default namespace. I think it is too intrusive for the name of this project to appear in every metric exported.

**Comment by ramonza** [comment]
Oh and right now it is impossible to set an empty namespace: we select "OpenCensus" as a default if the user supplies ""

**Comment by rakyll** [comment]
I will remove the default namespace.
