### ISSUE TITLE
zpages: prefix as explained in example_test.go doesn't work

### ISSUE THREAD

**Issue by ukai** [census-instrumentation/opencensus-go#559]
example test says

```go
// Both /debug/tracez and /debug/rpcz will be served.
http.Handle("/debug/", http.StripPrefix("/debug", zpages.Handler))
```
but /debug/tracez pages has link to /tracez, not /debug/tracez

**Comment by odeke-em** [comment]
@ukai thank you for reporting this.

However, I am a little confused, what part isn't working?

I ask because:
/tracez -- will give a 404
/rpcz    -- will give a 404
/debug/tracez -- will serve the content of /tracez
/debug/rpcz    -- will serve the content of /rpcz

Also what version of Go are you using?

**Comment by ukai** [comment]
/debug/tracez shows contents of /tracez. its content (if it got some data) contains links to /tracez?.... (404), which should be links to /debug/tracez?....
