### ISSUE TITLE
Cumulative metrics as exported by OpenCensus are not really useful in Stackdriver

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#576]
According to https://cloud.google.com/monitoring/api/v3/metrics-details (as well as independent reports in the Gitter), Stackdriver UI doesn't really support Cumulative metrics, at least not for "charting and alerting" (what exactly are they supported for then?)

Since OC only exports cumulative metrics the Stackdriver exporter doesn't really work right now.

**Comment by songy23** [comment]
Conceptually I think it's reasonable to map cumulative stats to cumulative Stackdriver metrics. When it comes to charting, Stackdriver will ignore their `MetricKind` and just treat these metrics as single data point (Gauge), and won't do any aggregation on it, which is also what we want, since we have already done aggregation on our side.

For example, consider sum cumulative stats:
- We record a measure value of 5.0, and export cumulative sum (5.0) to Stackdriver;
- We record another measure value of 3.0, and export cumulative sum (8.0) to Stackdriver.
In this case, two data points 5.0 and 8.0 will be added to Stackdriver charts, while if Stackdriver do aggregation again, these values will be (incorrectly) 5.0 and 13.0.

**Comment by ramonza** [comment]
> Conceptually I think it's reasonable to map cumulative stats to cumulative Stackdriver metrics. 
@songy23 did you mean "map cumulative stats to Guage Stackdriver metrics"?

**Comment by songy23** [comment]
No, I think cumulative stats should be mapped to cumulative Stackdriver metrics, to avoid confusion. In addition to charts, users can also get Stackdriver metrics by calling Stackdriver APIs, and I think it's confusing to see cumulative OpenCensus stats wrapped to gauge Stackdriver metrics.

Charts (and probably SD backend) don't make use of `MetricKind` type, so I think it's just an indicator of stats type, and it should match the stats type in OpenCensus.

**Comment by ramonza** [comment]
> Charts (and probably SD backend) don't make use of MetricKind type, so I think it's just an indicator of stats type, and it should match the stats type in OpenCensus.

This seems to be the case (@bogdandrutu showed me his working dashboard) but the docs claim otherwise (linked from the original issue, search for the word "cumulative"). I have pinged someone on the Stackdriver team about this.

**Comment by groob** [comment]
It might be the case that some customers have a new version of stackdriver enabled that supports this? My understanding is that Cumulative metrics are queryable via the API but that charts are broken. 

In any case, I'm not able to create a chart:

![screenshot 2018-03-13 14 50 28](https://user-images.githubusercontent.com/1526945/37363379-29fb7932-26ce-11e8-8f54-caf7c1834ada.png)

Not an issue for the census team, just sharing what I and likely other customers of Stackdriver see.

**Comment by ramonza** [comment]
Reply from the Stackdriver team is that this doc is misleading. 

From the internal bug report:

> you can't directly chart or alert on a cumulative metric -- but the cumulative metric can be input to an aggregation that makes it non-cumulative, and you can chart/alert on that result

**Comment by groob** [comment]
You're right. I was able to create a `view.CountAggregation` that shows data in the stackdriver charts. It's not a proper counter, but it works!

**Comment by ramonza** [comment]
@groob can this issue be closed?

**Comment by groob** [comment]
I think so!
