### ISSUE TITLE
Rename view.Subscribe to view.Register

### ISSUE THREAD

**Issue by ramonza** [census-instrumentation/opencensus-go#612]
To keep consistency with Java and C++, we need to rename view.Subscribe to view.Register and remove the existing deprecated Register functions.

**Comment by bogdandrutu** [comment]
I have a question and I would like to hear others opinion on this. Do we need to have two different functions?
* one to create the view struct
* one to register the view

C++ has only one:
* https://github.com/census-instrumentation/opencensus-cpp/blob/master/opencensus/stats/view.h#L25

Java has two as well.

**Comment by songy23** [comment]
If we want to support updating/removing a registered view, I think we need two different functions.

**Comment by odeke-em** [comment]
@bogdandrutu 
>I have a question and I would like to hear others opinion on this. Do we need to have two different functions?
>
>one to create the view struct

Doesn't seem necessary since the restrictions of creating views were removed hence a struct/class can be created just as an object.
Currently, views are created as structs in this repo just like they are created as classes in the CPP implementation
https://github.com/census-instrumentation/opencensus-cpp/blob/95f206606a7e34544d20bdeb109d3677c43b3110/opencensus/stats/view.h#L28
https://github.com/census-instrumentation/opencensus-cpp/blob/51c296f55bb421680f1a2b857207c76e3f1cc006/opencensus/stats/view_descriptor.h#L80-L84
The Go and CPP implementations invoke Register and RegisterForExporter respectively, so both have one function.

>one to register the view

This one is necessary

@songy23 
>If we want to support updating/removing a registered view, I think we need two different functions.

I believe that's what Unregister does, and that's already present for the Go implementation, am not sure what the CPP nor what the Java version does.
