### ISSUE TITLE
exporter/stackdriver: need an override for metric prefix

### ISSUE THREAD

**Issue by jkohen** [census-instrumentation/opencensus-go#836]
The Stackdriver exporter has a `MetricPrefix` field that's intended to be used in the metric name ([docs](https://github.com/census-instrumentation/opencensus-go/blob/10cec2c05ea2cfb8b0d856711daedc49d8a45c56/exporter/stackdriver/stackdriver.go#L77)), but it seems to be used as an override for `DisplayName` ([source](https://github.com/census-instrumentation/opencensus-go/blob/10cec2c05ea2cfb8b0d856711daedc49d8a45c56/exporter/stackdriver/stats.go#L268)).

The metric prefix seems to always be `custom.googleapis.com/opencensus` ([source](https://github.com/census-instrumentation/opencensus-go/blob/10cec2c05ea2cfb8b0d856711daedc49d8a45c56/exporter/stackdriver/stats.go#L364)).

I suspect this is a bug, not an intended behavior. Is it possible to change it? I could contribute the fix, if it's acceptable.
@fabxc

**Comment by songy23** [comment]
@jkohen I think this is intended. The `MetricPrefix` field is only for overriding the prefix of `DisplayName` at first. For metric name, the prefix `custom.googleapis.com/` is necessary since the Stackdriver exporter uploads metrics as custom metrics. Stackdriver backend will return an error if the metric name doesn't start with `custom.googleapis.com/`. You can send a PR to override the `opencensus/` namespace though (we already did that for [Prometheus exporter](https://github.com/census-instrumentation/opencensus-go/pull/665)).

**Comment by ramonza** [comment]
Related maybe: https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/22

**Comment by jkohen** [comment]
Yang Song, it's not true that you can't override the custom.googleapis.com
prefix. For instance, external.googleapis.com/prometheus/ is also
acceptable, and the list will continue to expand to accommodate cases like
the one Ramon linked to. I think MetricPrefix should override the entire
thing.

I don't really understand the use case for overridding DisplayName. Can you
expand on that? And do you disagree that the documentation for MetricPrefix
is misleading?

PS: OC should be using external.googleapis.com/opencensus by default (but
that's a separate issue).

**Comment by songy23** [comment]
> it's not true that you can't override the custom.googleapis.com
prefix. For instance, external.googleapis.com/prometheus/ is also
acceptable,

That's not true. Currently if you upload some metrics starting with `external.googleapis.com/opencensus` to Stackdriver, you will get a `Permission_Denied` error. [Stackdriver documentation](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors#MetricDescriptor) said:
>  All user-defined custom metric types have the DNS name custom.googleapis.com.

> I don't really understand the use case for overridding DisplayName. Can you
expand on that? And do you disagree that the documentation for MetricPrefix
is misleading?

This is brought up by https://github.com/census-instrumentation/opencensus-go/issues/582 and fixed in https://github.com/census-instrumentation/opencensus-go/pull/583. Agree that documentation is misleading, it should be "MetricPrefix overrides the OpenCensus prefix of the display name of a metric." instead.

> PS: OC should be using external.googleapis.com/opencensus by default (but
that's a separate issue).

There's an ongoing discussion about defining default OC metrics in Stackdriver, and @ramonza is leading that. However as I mentioned earlier, for now all the metrics need to be under `custom.googleapis.com`.

**Comment by jkohen** [comment]
It is not true that all metrics need to be under `custom.googleapis.com`, see the [Stackdriver documentation](https://cloud.google.com/monitoring/api/metrics_other). I believe Create should work for MetricDescriptor, I'll file a documentation bug.

The list of prefixes will continue to expand. It'd be sad to end up with two more "metric prefix" fields: one to modify `DisplayName`, one to replace `opencensus`, and one to replace `custom.googleapis.com`

I still find changing the prefix of DisplayName a very marginal use case, and to be honest it seems hacky to use the display name to group metrics this way. It's sad `MetricPrefix` is used for that, because "metric" != "metric descriptor documentation".

**Comment by songy23** [comment]
I see your point here. Sorry the "external metrics list" concept is totally new to me, and I didn't realize you can put any custom metrics under "external.googleapis.com". If you're confident that all your metrics (probably including all the gRPC metrics) should be under some other systems (e.g Prometheus, Agent), I'm fine with prefixing the metric name with them.

> I still find changing the prefix of DisplayName a very marginal use case, and to be honest it seems hacky to use the display name to group metrics this way.

This is brought up by an external user, though I'm not sure about their use case. 

> It'd be sad to end up with two more "metric prefix" fields: one to modify DisplayName, one to replace opencensus, and one to replace custom.googleapis.com

Unfortunately, for backwards-compatibility, we need to add another "metric prefix" field, since users can put any arbitrary prefix the current "MetricPrefix" field. Changing the behavior of the existing "MetricPrefix" field may break their application.

**Comment by ramonza** [comment]
Just an aside but in future let's have all Stackdriver discussion on the Stackdriver repo here: https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/

We are scheduled to remove the legacy embedded Stackdriver exporter that lives here soon. This issue will probably need to be closed and moved over as well.

**Comment by ramonza** [comment]
Moved this discussion to related issues on the Stackdriver repo.
