### ISSUE TITLE
Add Float64Attribute

### ISSUE THREAD

**Issue by toffaletti** [census-instrumentation/opencensus-go#900]
**Is your feature request related to a problem? Please describe.**
I need to add attributes that represent floating point numbers.

**Describe the solution you'd like**
`func Float64Attribute(key string, value float64) Attribute`

**Describe alternatives you've considered**
1. Using strconv to turn the float into a string for use with `StringAttribute`.
2. Turning the float64 into int64 losing decimal precision.

**Additional context**
OpenTracing has support for many additional types (including float64) https://godoc.org/github.com/opentracing/opentracing-go/log#Field

**Comment by bogdandrutu** [comment]
Started a discussion to add support for this.

**Comment by bogdandrutu** [comment]
The main specs issue was approved https://github.com/census-instrumentation/opencensus-specs/issues/172. Please start adding implementation for this.

**Comment by rakyll** [comment]
Also please note that this work also requires us to update all the Go trace exporter implementations.

**Comment by ramonza** [comment]
good point @rakyll - it's kind of a breaking change because the trace exporters will switch on the type. 

We need to do this while maintaining backwards compatibility.

Initial idea: introduce a notion of exporter capabilities that allows the exporters to communicate what they support? Something like:
```go
type HasCapabilities interface {
  func Capabilties() map[ExporterCapability]bool
}
type ExporterCapability int
const SupportsFloatAttributes ExporterCapability = 0
```

If the exporter does not implement that interface, we assume it has no special capabilities. 

It's a lot of overhead but it seems like a generally useful mechanism. Open to alternative suggestions but I really don't want to introduce a breaking change that requires coordinated fixes across multiple repos. 

This is a big disadvantage of relying on exporters downcasting things. We do this for stats exporter aggregation types as well. We should try to avoid this in future.

**Comment by rakyll** [comment]
Adding more functionality for this sounds like too much work. Instead we can coordinate and land the required change for all the exporters. We need to just file issues or create PRs on exporters that we don't maintain ourselves, like Datadog's.
