### ISSUE TITLE
exporter/stackdriver: duration <60s causes duplicate timeseries to be written

### ISSUE THREAD

**Issue by jadekler** [census-instrumentation/opencensus-go#909]
I have a simple pubsub app using stackdriver exporter and some views. When I set `view.SetReportingPeriod(time.Second)`, I begin to see the following warning printed:

```
2018/09/11 14:45:01 Failed to export to Stackdriver: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[4] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[4]; Field timeSeries[5] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[5]; Field timeSeries[6] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[6]; Field timeSeries[7] had an invalid value: Duplicate TimeSeries encountered. Only one point can be written per TimeSeries per request.: timeSeries[7]
```

[The full program is here.](https://gist.github.com/jadekler/5636acc62eb0048cad15206ef5587650)

Things I would expect:

- Either this warning should not appear (why are we sending the same stats twice?)
- Or this should be documented in `view.SetReportingPeriod` (what is the lowest safe reporting duration?)

**Comment by odeke-em** [comment]
Thank you for the bug report @jadekler and great to hear from you!

So this is a bug report for the Stackdriver exporter which lives under  https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver. The lowest safe reporting duration for Stackdriver is 60 seconds as per https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/36. Unfortunately we've had it in examples as 1 second because asking folks to wait for >=60seconds is way too much.

**Comment by odeke-em** [comment]
@jadekler I've also updated the website and Stackdriver examples on there, as necessary/possible https://github.com/census-instrumentation/opencensus-website/pull/323.

**Comment by odeke-em** [comment]
Awesome, with those updates and also your PR in https://github.com/census-instrumentation/opencensus-go/pull/910 @jadekler can we close this now?

**Comment by jadekler** [comment]
Yes! Thanks Emmanuel!
