### ISSUE TITLE
exporter/prometheus: Avoid missing metrics

### ISSUE THREAD

**Issue by negz** [census-instrumentation/opencensus-go#935]
**Describe the bug**
As best I can tell the Go Prometheus metrics exporter does not export views as lines in the Prometheus exposition format until something actually happens to the view's measurement. Put otherwise, a view with a count aggregation metric will never expose an unlabelled counter at 0; each counter will spring into existence when it is first incremented. This goes against [Prometheus's recommendation](https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics) that instrumentation 'avoid missing metrics'. (I debated raising this as a feature request, given it _is_ only a guideline.)

**To Reproduce**
1. Download [the Prometheus exporter example code](https://raw.githubusercontent.com/census-instrumentation/opencensus-go/140879bf49cb17276aaf28b5f6a04e251ff98473/exporter/prometheus/example/main.go).
2. Apply the following diff:
```diff
--- ogmain.go   2018-09-26 01:37:35.000000000 -0700
+++ main.go     2018-09-26 01:37:10.000000000 -0700
@@ -17,9 +17,7 @@
 package main
 
 import (
-       "context"
        "log"
-       "math/rand"
        "net/http"
        "time"
 
@@ -36,8 +34,6 @@
 )
 
 func main() {
-       ctx := context.Background()
-
        exporter, err := prometheus.NewExporter(prometheus.Options{})
        if err != nil {
                log.Fatal(err)
@@ -68,13 +64,6 @@
        // Set reporting period to report data at every second.
        view.SetReportingPeriod(1 * time.Second)
 
-       // Record some data points...
-       go func() {
-               for {
-                       stats.Record(ctx, videoCount.M(1), videoSize.M(rand.Int63()))
-                       <-time.After(time.Millisecond * time.Duration(1+rand.Intn(400)))
-               }
-       }()
 
        addr := ":9999"
        log.Printf("Serving at %s", addr)
```
3. `go run main.go`
4. Attempt to curl the metrics:
```bash
$ curl -v http://localhost:9999/metrics
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9999 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:9999
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 0
< Content-Type: text/plain; version=0.0.4; charset=utf-8
< Date: Wed, 26 Sep 2018 08:39:24 GMT
< 
* Connection #0 to host localhost left intact
```

**Expected behavior**
`video_size` and `video_count` are exposed as either zero or `NaN` value metrics with no labels per [Prometheus's recommendation](https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics).

**Additional context**
[This line](https://github.com/census-instrumentation/opencensus-go/blob/140879b/exporter/prometheus/prometheus.go#L121) in the Prometheus exporter seems suspiciously like it may be the culprit here. I have not spelunked enough to be sure of this.

**Comment by negz** [comment]
> Most Prometheus client libraries (including Go, Java, and Python) will automatically export a 0 for you for metrics with no labels.

I realised soon after raising this that this means Prometheus only exports sensible default values for metrics that _do not have labels_. I had originally interpreted it as meaning Prometheus client libraries would export an unlabelled version of a metric (even if that metric might grow labels eventually) with a sensible default value.

So, technically this bug report/feature request is still valid in that code such as the Prometheus exporter example that has no tags could benefit from exporting sensible default values, but in almost all of my actual use cases my metrics have tags/labels and thus initialising them is [up to me](https://www.robustperception.io/existential-issues-with-metrics).

**Comment by rakyll** [comment]
It seems like we still need to register the metric descriptors instead of returning at https://github.com/census-instrumentation/opencensus-go/blob/140879b/exporter/prometheus/prometheus.go#L128 even though there is no values collected on them.

**Comment by fabxc** [comment]
As your follow up correctly stated, Prometheus can also only do this for metrics without labels. That's because there's just no way to know which combinations of label values might possibly exist without the user explicitly providing that info.

Thus you'd have to write initialization code like [this](https://github.com/prometheus/prometheus/blob/v1.8.2/storage/local/storage.go#L368-L384), to create those series with a default value. For more than one label, you'd have to do nested for loops to achieve the same.

That also only works if you know all valid values for all labels beforehand, which you often don't. For example, new disks may be mounted at runtime under unknown paths.
Even if, it is often not feasible since instantiating series for all valid combination results in cardinality explosion. Suppose a HTTP request count metric with labels `status_code`, `path`, and `method`. For an application with 10 (templated) paths, we'd get about 100*10*9 valid combinations and would thus generate about 9000 series for that metric. Certainly that's way more than will ever encounter data.

Overall, while the guideline is nice, it's rarely used in practice and often entirely infeasible. If OC users want to ensure that series are exposed from the beginning, they can use the same initialization technique as for Prometheus by doing 0 measurement. Though admittedly that only works correctly for counters right now.  
Not sure whether this is important enough to add quirks to the API for.

**Comment by negz** [comment]
I agree with @fabxc's assessment. I raised this issue based under the mistaken assumption that Prometheus would expose unlabelled variants of metrics that would gain metrics over their lifetime. Upon a little reflection, that would be poor practice.

I'm going to close this issue because it sounds like it's not really an issue at all; more a feature request for a feature I don't actually need that has little practical value.

**Comment by cstyan** [comment]
:+1: @fabxc thanks for the detailed explanation!
